language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adi2911/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adi2911/react-client-test npm test

after_success:
  - docker build -t adi2911/react-client ./client
  - docker build -t adi2911/express-server ./server
  - docker build -t adi2911/worker ./worker
  - docker build -t adi2911/nginx ./nginx



