version: '3'
services:
  react-client:
    image: "adi2911/docker-client"
    mem_limit: 128m
    hostname: react-client
  express-server:
    image: "adi2911/docker-server"
    mem_limit: 128m
    hostname: express-server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT 
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD 
      - PGPORT=$PGPORT 
  worker:
    image: "adi2911/docker-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "adi2911/docker-nginx"
    mem_limit: 128m
    hostname: nginx
    ports: 
      - "80:80"
 